import type { Team } from "./Types";

export const sampleTeams: Team[] = [
  {
    _id: "1",
    teamId: "TM-A1B2C3",
    managerId: "MGR-001",
    name: "Thunder Strikers",
    logo: "https://placekitten.com/100/100",
    sport: "Cricket",
    description: "Aggressive players aiming for victory.",
    maxPlayers: 15,
    members: 10,
    state: "Karnataka",
    city: "Bangalore",
    stats: { totalMatches: 12, winRate: 75 },
    phase: "recruiting",
    created: "2025-09-10T10:00:00.000Z",
  },
  {
    _id: "2",
    teamId: "TM-D4E5F6",
    managerId: "MGR-002",
    name: "Golden Eagles",
    logo: "https://placekitten.com/101/100",
    sport: "Football",
    description: "Precision and teamwork define us.",
    maxPlayers: 18,
    members: 18,
    state: "Maharashtra",
    city: "Mumbai",
    stats: { totalMatches: 20, winRate: 60 },
    phase: "active",
    created: "2025-08-22T12:00:00.000Z",
  },
  {
    _id: "3",
    teamId: "TM-G7H8I9",
    managerId: "MGR-003",
    name: "Rapid Runners",
    logo: "https://placekitten.com/102/100",
    sport: "Cricket",
    description: "Speed and agility are our strengths.",
    maxPlayers: 12,
    members: 9,
    state: "Delhi",
    city: "Delhi",
    stats: { totalMatches: 8, winRate: 50 },
    phase: "recruiting",
    created: "2025-07-15T09:30:00.000Z",
  },
  {
    _id: "4",
    teamId: "TM-J1K2L3",
    managerId: "MGR-004",
    name: "Iron Titans",
    logo: "https://placekitten.com/103/100",
    sport: "Basketball",
    description: "Strength and endurance lead us to victory.",
    maxPlayers: 10,
    members: 10,
    state: "Tamil Nadu",
    city: "Chennai",
    stats: { totalMatches: 15, winRate: 80 },
    phase: "active",
    created: "2025-06-18T11:00:00.000Z",
  },
  {
    _id: "5",
    teamId: "TM-M4N5O6",
    managerId: "MGR-005",
    name: "Silver Sharks",
    logo: "https://placekitten.com/104/100",
    sport: "Football",
    description: "Aggressive offense, solid defense.",
    maxPlayers: 18,
    members: 16,
    state: "Gujarat",
    city: "Ahmedabad",
    stats: { totalMatches: 10, winRate: 70 },
    phase: "recruiting",
    created: "2025-05-20T10:30:00.000Z",
  },
  {
    _id: "6",
    teamId: "TM-P7Q8R9",
    managerId: "MGR-006",
    name: "Night Owls",
    logo: "https://placekitten.com/105/100",
    sport: "Cricket",
    description: "Playing under pressure is our forte.",
    maxPlayers: 14,
    members: 14,
    state: "West Bengal",
    city: "Kolkata",
    stats: { totalMatches: 18, winRate: 65 },
    phase: "active",
    created: "2025-04-12T08:45:00.000Z",
  },
  {
    _id: "7",
    teamId: "TM-S1T2U3",
    managerId: "MGR-007",
    name: "Storm Breakers",
    logo: "https://placekitten.com/106/100",
    sport: "Basketball",
    description: "Unstoppable force on the court.",
    maxPlayers: 10,
    members: 7,
    state: "Karnataka",
    city: "Mysore",
    stats: { totalMatches: 5, winRate: 40 },
    phase: "recruiting",
    created: "2025-03-08T14:00:00.000Z",
  },
  {
    _id: "8",
    teamId: "TM-V4W5X6",
    managerId: "MGR-008",
    name: "Red Raptors",
    logo: "https://placekitten.com/107/100",
    sport: "Cricket",
    description: "Quick reflexes and strategic plays.",
    maxPlayers: 15,
    members: 15,
    state: "Maharashtra",
    city: "Pune",
    stats: { totalMatches: 25, winRate: 85 },
    phase: "completed",
    created: "2025-02-15T09:15:00.000Z",
  },
  {
    _id: "9",
    teamId: "TM-Y7Z8A9",
    managerId: "MGR-009",
    name: "Blue Blazers",
    logo: "https://placekitten.com/108/100",
    sport: "Football",
    description: "Teamwork and tactics are key.",
    maxPlayers: 18,
    members: 18,
    state: "Delhi",
    city: "Noida",
    stats: { totalMatches: 12, winRate: 55 },
    phase: "active",
    created: "2025-01-10T16:00:00.000Z",
  },
  {
    _id: "10",
    teamId: "TM-B1C2D3",
    managerId: "MGR-010",
    name: "Green Giants",
    logo: "https://placekitten.com/109/100",
    sport: "Basketball",
    description: "Height and coordination dominate.",
    maxPlayers: 12,
    members: 10,
    state: "Tamil Nadu",
    city: "Coimbatore",
    stats: { totalMatches: 7, winRate: 45 },
    phase: "recruiting",
    created: "2025-10-01T12:00:00.000Z",
  },
];
