export const MANAGER_ROUTES = {
    GET_DETAILS: (managerId: string) => `/manager/${managerId}`,
    EDIT_DETAILS: (managerId: string) => `/manager/${managerId}`,
    GET_TEAMS: (managerId: string) => `/manager/teams/${managerId}`,
    GET_TEAM: (teamId: string) => `/manager/team/${teamId}/details`,
    CREATE_TEAM: '/manager/team',
    DELETE_TEAM: (teamId: string) => `/manager/team/${teamId}`,
    EDIT_TEAM: (teamId: string) => `/manager/team/${teamId}`,
    CREATE_TOURNAMENT: '/manager/tournament',
    GET_MY_TOURNAMENTS: (managerId: string) => `/manager/tournament/${managerId}`,
    GET_EXPLORE_TOURNAMENTS: (managerId: string) => `/manager/tournament/explore/${managerId}`,
    CANCEL_TOURNAMENT: (tournamentId: string) => `/manager/tournament/${tournamentId}`,
    EDIT_TOURNAMENT: (tournamentId: string) => `/manager/tournament/${tournamentId}`,
    TOURNAMENT_DETAILS: (tournamentId: string) => `/manager/tournament/${tournamentId}/details`,
    TOUTNAMENT_PAYMENT: (tournamentId: string) => `/manager/tournament/${tournamentId}/payment`,
    PAYMENT_STATUS: (registrationId: string) => `/manager/registration/${registrationId}/status`,
    REGISTERED_TEAMS: (tournamentId: string) => `/manager/tournament/${tournamentId}/teams`,
    REJECT_PLAYER: (playerId: string) => `/manager/team/${playerId}/reject`,
    REMOVE_PLAYER: (playerId: string) => `/manager/team/${playerId}/remove`,
    APPROVE_PLAYER: (playerId: string) => `/manager/team/${playerId}/approve`,
    UPDATE_PLAYER: (playerId: string) => `/manager/team/${playerId}/swap`,
    CREATE_MATCHES: (tournamentId: string) => `/manager/tournament/${tournamentId}/matches`,
    GET_MATCHES: (tournamentId: string) => `/manager/tournament/${tournamentId}/matches`,
    GET_LEADERBOARD: (tournamentId: string) => `/manager/tournament/${tournamentId}/leaderboard`,
    CREATE_FIXTURE: (tournamentId: string) => `/manager/tournament/${tournamentId}/fixture`,
    GET_FIXTURES: (tournamentId: string) => `/manager/tournament/${tournamentId}/fixture`,
} as const;