import { UserRepository } from "../repositories/mongo/UserRepository.js";
import { AdminRepository } from "../repositories/mongo/AdminRepository.js"; 
import { PlayerRepository } from "../repositories/mongo/PlayerRepository.js";
import { ManagerRepository } from "../repositories/mongo/ManagerRepository.js";
import { OtpRepository } from "../repositories/mongo/OtpRepository.js"; 
import { TeamRepository } from "../repositories/mongo/TeamRepository.js";
import { NotificationRepository } from "../repositories/mongo/NotificationRepository.js";
import { RegistrationRepository } from "../repositories/mongo/RegistrationRepository.js";
import { FixturesRepository } from "../repositories/mongo/FixturesRepository.js";
import { MatchesRepository } from "../repositories/mongo/MatchesRepository.js";
import { ChatRepository } from "../repositories/mongo/ChatRepository.js";
import { MessageRepository } from "../repositories/mongo/MessageRepository.js";
import { PlanRepository } from "../repositories/mongo/PlanRepository.js";
import { SubscriptionRepository } from "../repositories/mongo/SubscriptionRepository.js";
import { LeaderboardRepository } from "../repositories/mongo/LeaderboardRepository.js";
import { MatchStatsRepository } from "../repositories/mongo/MatchStatsRepo.js";
import { SettingsRepository } from "../repositories/mongo/SettingsRepository.js";
import { TransactionRepository } from "../repositories/mongo/TransactionRepository.js";
import { DashboardRepository } from "../repositories/mongo/DashboardRepository.js";
import { FinancialRepository } from "../repositories/mongo/FinancialRepository.js";
import { WalletRepository } from "../repositories/mongo/WalletRepository.js";
import { container } from "tsyringe"; 
import { DI_TOKENS } from "../../domain/constants/Identifiers.js";
import { PointsTableRepository } from "../../infra/repositories/mongo/PointsTableRepository.js";
import { TournamentRepository } from "../repositories/mongo/TournamentRepo.js";
import { PayoutRepository } from "../repositories/mongo/PayoutRepository.js";
import { PayoutMappingRepository } from "../repositories/mongo/PayoutMappingRepository.js";



// B. Repositories
container.register(DI_TOKENS.UserRepository, { useClass: UserRepository });
container.register(DI_TOKENS.AdminRepository, { useClass: AdminRepository });
container.register(DI_TOKENS.PlayerRepository, { useClass: PlayerRepository });
container.register(DI_TOKENS.ManagerRepository, { useClass: ManagerRepository });
container.register(DI_TOKENS.OtpRepository, { useClass: OtpRepository });
container.register(DI_TOKENS.TeamRepository, { useClass: TeamRepository });
container.register(DI_TOKENS.NotificationRepository, { useClass: NotificationRepository });
container.register(DI_TOKENS.TournamentRepository, { useClass: TournamentRepository });
container.register(DI_TOKENS.RegistrationRepository, { useClass: RegistrationRepository });
container.register(DI_TOKENS.FixturesRepository, { useClass: FixturesRepository });
container.register(DI_TOKENS.MatchesRepository, { useClass: MatchesRepository });
container.register(DI_TOKENS.MatchStatsRepository, { useClass: MatchStatsRepository });
container.register(DI_TOKENS.ChatRepository, { useClass: ChatRepository });
container.register(DI_TOKENS.MessageRepository, { useClass: MessageRepository });
container.register(DI_TOKENS.PlanRepository, { useClass: PlanRepository });
container.register(DI_TOKENS.SubscriptionRepository, { useClass: SubscriptionRepository });
container.register(DI_TOKENS.LeaderboardRepository, { useClass: LeaderboardRepository });
container.register(DI_TOKENS.SettingsRepository, { useClass: SettingsRepository });
container.register(DI_TOKENS.TransactionRepository, { useClass: TransactionRepository });
container.register(DI_TOKENS.DashboardRepository, { useClass: DashboardRepository });
container.register(DI_TOKENS.FinancialRepository, { useClass: FinancialRepository });
container.register(DI_TOKENS.WalletRepository, { useClass: WalletRepository });
container.register(DI_TOKENS.PointsTableRepository, { useClass: PointsTableRepository });
container.register(DI_TOKENS.PayoutRepository, { useClass: PayoutRepository });
container.register(DI_TOKENS.PayoutMappingRepository, { useClass: PayoutMappingRepository });
