import { UserRepositoryMongo } from "../repositories/mongo/UserRepositoryMongo.js";
import { AdminRepositoryMongo } from "../repositories/mongo/AdminRepositoryMongo.js";
import { PlayerRepositoryMongo } from "../repositories/mongo/PlayerRepositoryMongo.js";
import { ManagerRepositoryMongo } from "../repositories/mongo/ManagerRepositoryMongo.js";
import { OtpRepositoryMongo } from "../repositories/mongo/OtpRepositoryMongo.js";
import { TeamRepositoryMongo } from "../repositories/mongo/TeamRepositoryMongo.js";
import { NotificationRepository } from "../repositories/mongo/NotificationRepository.js";
import { TournamentRepositoryMongo } from "../repositories/mongo/TournamentRepoMongo.js";
import { RegistrationRepository } from "../repositories/mongo/RegistrationRepository.js";
import { FixturesRepositoryMongo } from "../repositories/mongo/FixturesRepositoryMongo.js";
import { MatchesRepositoryMongo } from "../repositories/mongo/MatchesRepositoryMongo.js";
import { ChatRepositoryMongo } from "../repositories/mongo/ChatRepositoryMongo.js";
import { MessageRepositoryMongo } from "../repositories/mongo/MessageRepositoryMongo.js";
import { PlanRepository } from "../repositories/mongo/PlanRepository.js";
import { SubscriptionRepository } from "../repositories/mongo/SubscriptionRepository.js";
import { LeaderboardRepository } from "../repositories/mongo/LeaderboardRepository.js";
import { MatchRepoMongo } from "../repositories/mongo/MatchStatsRepo.js";
import { SettingsRepository } from "../repositories/mongo/SettingsRepository.js";
import { TransactionRepository } from "../repositories/mongo/TransactionRepository.js";
import { DashboardRepository } from "../repositories/mongo/DashboardRepository.js";
import { FinancialRepository } from "../repositories/mongo/FinancialRepository.js";
import { WalletRepository } from "../repositories/mongo/WalletRepository.js";
import { container } from "tsyringe"; 
import { DI_TOKENS } from "../../domain/constants/Identifiers.js";
import { PointsTableRepository } from "../../infra/repositories/mongo/PointsTableRepository.js";



// B. Repositories
container.register(DI_TOKENS.UserRepository, { useClass: UserRepositoryMongo });
container.register(DI_TOKENS.AdminRepository, { useClass: AdminRepositoryMongo });
container.register(DI_TOKENS.PlayerRepository, { useClass: PlayerRepositoryMongo });
container.register(DI_TOKENS.ManagerRepository, { useClass: ManagerRepositoryMongo });
container.register(DI_TOKENS.OtpRepository, { useClass: OtpRepositoryMongo });
container.register(DI_TOKENS.TeamRepository, { useClass: TeamRepositoryMongo });
container.register(DI_TOKENS.NotificationRepository, { useClass: NotificationRepository });
container.register(DI_TOKENS.TournamentRepository, { useClass: TournamentRepositoryMongo });
container.register(DI_TOKENS.RegistrationRepository, { useClass: RegistrationRepository });
container.register(DI_TOKENS.FixturesRepository, { useClass: FixturesRepositoryMongo });
container.register(DI_TOKENS.MatchesRepository, { useClass: MatchesRepositoryMongo });
container.register(DI_TOKENS.MatchStatsRepository, { useClass: MatchRepoMongo });
container.register(DI_TOKENS.ChatRepository, { useClass: ChatRepositoryMongo });
container.register(DI_TOKENS.MessageRepository, { useClass: MessageRepositoryMongo });
container.register(DI_TOKENS.PlanRepository, { useClass: PlanRepository });
container.register(DI_TOKENS.SubscriptionRepository, { useClass: SubscriptionRepository });
container.register(DI_TOKENS.LeaderboardRepository, { useClass: LeaderboardRepository });
container.register(DI_TOKENS.SettingsRepository, { useClass: SettingsRepository });
container.register(DI_TOKENS.TransactionRepository, { useClass: TransactionRepository });
container.register(DI_TOKENS.DashboardRepository, { useClass: DashboardRepository });
container.register(DI_TOKENS.FinancialRepository, { useClass: FinancialRepository });
container.register(DI_TOKENS.WalletRepository, { useClass: WalletRepository });
container.register(DI_TOKENS.PointsTableRepository, { useClass: PointsTableRepository });
