import { container } from "tsyringe"; 
import { DI_TOKENS } from "../../domain/constants/Identifiers.js";

//  Services 
import { UserManagementService } from "../services/UserManagementService.js";
import { MatchScoreService } from "../services/MatchStatsService.js";
import { TeamSetupService } from "../services/TeamSetupServices.js";
import { PlayerService } from "../services/PlayerService.js";
import { LogoutService } from "../services/LogoutService.js";
import { GoogleAuthService } from "../services/GoogleAuthServices.js";
import { FacebookServices } from "../services/FacebookServices.js";
import { LiveStreamService } from "../services/LiveStreamService.js";
import { TransactionService } from "../services/TransactionService.js";
import { SubscriptionPaymentService } from "../services/SubscriptionService.js";
import { MatchPlayerServices } from "../services/MatchPlayerServices.js";
import { GetAvailablePlayersService } from "../services/GetAvailablePlayersService.js";
import { TournamentRegistrationValidator } from "../services/TournamentRegistrationValidator.js";
import { PlayerTeamServices } from "../services/PlayerTeamServices.js";
import { UserServices } from "../services/UserServices.js";
import { UserAuthServices } from "../services/UserAuthServices.js";
import { GetPlansAndUserSubscription } from "../services/GetPlansAndUserSubscription.js";
import { StartTournament } from "../../infra/services/StartTournament.js";
import { TournamentRefundService } from "../../infra/services/TournamentRefundService.js";
import { PayoutMethodResolver } from "../providers/PayoutMethodResolver.js";
import { WebhookService } from "../services/WebhookService.js";
import { ProfileInitializationService } from "../services/ProfileInitializationService.js";

// registrations
container.register(DI_TOKENS.UserManagementService, { useClass: UserManagementService });
container.register(DI_TOKENS.MatchScoreService, { useClass: MatchScoreService });
container.register(DI_TOKENS.MatchPlayerServices, { useClass: MatchPlayerServices });
container.register(DI_TOKENS.TeamSetupService, { useClass: TeamSetupService });
container.register(DI_TOKENS.GetAvailablePlayersService, { useClass: GetAvailablePlayersService });
container.register(DI_TOKENS.TournamentRegistrationValidator, { useClass: TournamentRegistrationValidator });
container.register(DI_TOKENS.PlayerService, { useClass: PlayerService });
container.register(DI_TOKENS.LogoutService, { useClass: LogoutService });
container.register(DI_TOKENS.PlayerTeamServices, { useClass: PlayerTeamServices });
container.register(DI_TOKENS.UserServices, { useClass: UserServices });
container.register(DI_TOKENS.UserAuthServices, { useClass: UserAuthServices });
container.register(DI_TOKENS.GoogleAuthService, { useClass: GoogleAuthService });
container.register(DI_TOKENS.FacebookServices, { useClass: FacebookServices });
container.register(DI_TOKENS.LiveStreamService, { useClass: LiveStreamService });
container.register(DI_TOKENS.TransactionService, { useClass: TransactionService });
container.register(DI_TOKENS.SubscriptionPaymentService, { useClass: SubscriptionPaymentService });
container.register(DI_TOKENS.GetPlansAndUserSubscription, { useClass: GetPlansAndUserSubscription });
container.register(DI_TOKENS.StartTournament, { useClass: StartTournament });
container.register(DI_TOKENS.TournamentRefundService, { useClass: TournamentRefundService });
container.register(DI_TOKENS.PayoutMethodResolver, { useClass: PayoutMethodResolver });
container.register(DI_TOKENS.WebhookService, { useClass: WebhookService });
container.register(DI_TOKENS.ProfileInitializationService, { useClass: ProfileInitializationService });
