import { API_PREFIX } from "../../utils/api";

export const MANAGER_ROUTES = {
    GET_DETAILS: (managerId: string) => `${API_PREFIX}/manager/${managerId}`,
    EDIT_DETAILS: (managerId: string) => `${API_PREFIX}/manager/${managerId}`,
    GET_TEAMS: (managerId: string) => `${API_PREFIX}/manager/teams/${managerId}`,
    GET_PAYMENTS: (managerId: string) => `${API_PREFIX}/manager/financials/${managerId}`,
    GET_TEAM: (teamId: string) => `${API_PREFIX}/manager/team/${teamId}/details`,
    CREATE_TEAM: `${API_PREFIX}/manager/team`,
    DELETE_TEAM: (teamId: string) => `${API_PREFIX}/manager/team/${teamId}`,
    EDIT_TEAM: (teamId: string) => `${API_PREFIX}/manager/team/${teamId}`,
    CREATE_TOURNAMENT: `${API_PREFIX}/manager/tournament`,
    START_TOURNAMENT: `${API_PREFIX}/manager/tournament/start`,
    GET_MY_TOURNAMENTS: (managerId: string) => `${API_PREFIX}/manager/tournament/${managerId}`,
    GET_DASHBOARD_ANALYTICS: (managerId: string) => `${API_PREFIX}/manager/tournament/${managerId}/analytics`,
    GET_EXPLORE_TOURNAMENTS: (managerId: string) => `${API_PREFIX}/manager/tournament/explore/${managerId}`,
    CANCEL_TOURNAMENT: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}`,
    EDIT_TOURNAMENT: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}`,
    TOURNAMENT_DETAILS: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/details`,
    TOUTNAMENT_PAYMENT: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/payment`,
    PAYMENT_STATUS: (registrationId: string) => `${API_PREFIX}/manager/registration/${registrationId}/status`,
    REGISTERED_TEAMS: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/teams`,
    REJECT_PLAYER: (playerId: string) => `${API_PREFIX}/manager/team/${playerId}/reject`,
    REMOVE_PLAYER: (playerId: string) => `${API_PREFIX}/manager/team/${playerId}/remove`,
    APPROVE_PLAYER: (playerId: string) => `${API_PREFIX}/manager/team/${playerId}/approve`,
    ADD_PLAYER: (playerId: string) => `${API_PREFIX}/manager/team/${playerId}/add`,
    UPDATE_PLAYER: (playerId: string) => `${API_PREFIX}/manager/team/${playerId}/swap`,
    CREATE_MATCHES: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/matches`,
    GET_MATCHES: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/matches`,
    GET_LEADERBOARD: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/leaderboard`,
    GET_POINTS_TABLE: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/points-table`,
    CREATE_FIXTURE: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/fixture`,
    GET_FIXTURES: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/fixture`,
    GET_AVAILABLE_PLAYERS: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/available-players`,
    GET_MATCH_RESULT: (tournamentId: string) => `${API_PREFIX}/manager/tournament/${tournamentId}/results`,
    AVAILABLE_UMPIRES: `${API_PREFIX}/manager/tournament/umpires`,
} as const;